### PR TITLE
Fixes RDS::DBParameterGroup resource definition.

### PR DESCRIPTION
**Pull request by shadone**
That parameter is a freeform object. Its content is passed to the database as a
parameter dictionary.

### CODE REVIEW

**Comment by aliak00** [comment]
Yay! Pull/1 :)

Damn, strange that [this line](https://github.com/aliak00/kosmo/blob/master/lib/kosmoform/lib/types.js#L350) doesn't catch that

I looked at docs, it says JSON object, but then in the same friggin sentence they change their mind and say object of string key-value pairs :/ Gotta love the cf docs.

Maybe it should be `types.object('key-value-pair', { Key: { type: types.string }, Value: { type: types.string } ))` ? or something instead?

**Comment by shadone** [comment]
The linked line won't be called - the types was set to `type.object` instead of `type.object()` (or better `type.object('foobar-name')`).

The AWS docs are indeed confusing. It is actually an object with key-value pairs in it; both key and value are string types. For example:

```
            var dbParameterGroup = nova.resources.rds.DBParameterGroup(mkname('ParameterGroup'), {
                Description: 'Production database',
                Family: 'postgres9.3',
                Parameters: {
                    'statement_timeout': '600000',
                },
            });
```

**Comment by aliak00** [comment]
> The linked line won't be called - the types was set to type.object instead of type.object() (or better type.object('foobar-name'))

Dammit. True.

**Comment by aliak00** [comment]
See Pull #2

**Pull request closed without merging**
